
version: '3'
services:
	image: client:latest
    container_name: client_container
    restart: always
    ports:
     - "3002:3000"
    networks:
     - "rabbit-comunication"
	 
	image: server:latest
    container_name: server_container
    restart: always
    ports:
     - "3001:3000"
    networks:
     - "rabbit-comunication"
networks:
  rabbit-comunication:
